check features exist before start it

diff --git a/utils/jenkins_exec_features b/utils/jenkins_exec_features
--- a/utils/jenkins_exec_features
+++ b/utils/jenkins_exec_features
@@ -38,6 +38,12 @@ done
 
 export PYTHONPATH=$PYTHONPATH_STR
 
+
+if [ ! -d "features" ]; then
+    echo "ERROR: no features found"
+    exit 1
+fi
+
 if [ $FEATURE_NAME == 'post_wizard' ]; then
     python /data/xivo-acceptance/utils/prerequisite.py
 fi
