extract commands in function instead of variables

diff --git a/utils/jenkins_check_xivo b/utils/jenkins_check_xivo
--- a/utils/jenkins_check_xivo
+++ b/utils/jenkins_check_xivo
@@ -20,18 +20,26 @@
 # Usage : $0 XIVO_HOST
 # Exit status is 0 if XiVO is properly installed on remote XIVO_HOST, 1 otherwise
 
-xivo_is_installed="$(ssh $1 /usr/bin/dpkg-query -W '-f=\${Status}\\n' xivo)"
+xivo_host="$1"
 
-if ! [ "$xivo_is_installed" = "install ok installed" ] ; then
-        # xivo not installed
-        exit 1
+function xivo_is_installed () {
+    [ $(ssh $xivo_host /usr/bin/dpkg-query -W '-f=\${Status}\\n' xivo) = "install ok installed" ]
+}
+
+function packaging_errors () {
+    ssh $xivo_host apt-get install -fs -qq
+}
+
+if ! xivo_is_installed ; then
+    echo "Package xivo is not installed"
+    exit 1
 fi
 
-is_error="$(ssh $1 apt-get install -fs -qq)"
-
-if [ -n "$is_error" ] ; then
-        # errors with installed packages
-        exit 1
+packaging_errors="$(packaging_errors)"
+if [ -n "$packaging_errors" ] ; then
+    echo "Packaging errors:"
+    echo "$packaging_errors"
+    exit 1
 fi
 
 exit 0
